management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=ALWAYS
management.info.env.enabled=true
info.application.name=AuthJSB
info.application.description=A demo OAUTH 2 server.
info.application.author=Naveen Paulraj
info.application.version='@project.version@'
#
info.app.version=6.0
info.company.name=N4SoftSol
info.company.environment=Production
#
management.endpoints.web.cors.allowed-origin-patterns=https://*.n4softsol.com,http://localhost:4200
management.endpoints.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
management.endpoints.web.cors.allowed-headers=*
management.endpoints.web.cors.allow-credentials=true
#
spring.profiles.active=dev